using System.Data;

namespace Griffin.Data.Mapper.Values
{
    /// <summary>
    ///     Mapping for a class property
    /// </summary>
    public interface IPropertyMapping
    {
        /// <summary>
        ///     Can write to property (i.e. update it from the table column)
        /// </summary>
        bool CanWrite { get; }

        /// <summary>
        ///     Can read from the property (i.e. create UPDATE/INSERT queries)
        /// </summary>
        bool CanRead { get; }

        /// <summary>
        ///     Used when fetching items
        /// </summary>
        bool IsPrimaryKey { get; set; }

        /// <summary>
        ///     PK value is generated by the DB, i.e. do not insert it.
        /// </summary>
        bool IsAutoIncrement { get; set; }

        /// <summary>
        ///     Used to convert the database value to the type used by the property
        /// </summary>
        ValueHandler ColumnToPropertyAdapter { get; set; }


        /// <summary>
        ///     Used to convert the property to the type used by the column.
        /// </summary>
        ValueHandler PropertyToColumnAdapter { get; set; }


        /// <summary>
        ///     Name of the property in the entity
        /// </summary>
        string PropertyName { get; set; }

        /// <summary>
        ///     Set if the column name is different from the property name
        /// </summary>
        string ColumnName { get; set; }

        /// <summary>
        ///     If DBNull fields should be processed or ignored.
        /// </summary>
        /// <remarks>
        ///     <para>
        ///         <c>true</c> means that the property should be assigned with <c>NullValue</c> if the column is <c>DBNull.</c>
        ///     </para>
        /// </remarks>
        bool IsNullable { get; set; }

        /// <summary>
        ///     Value used when converting to/from <c>DBNull</c>.
        /// </summary>
        object NullValue { get; set; }

        /// <summary>
        ///     Convert the value in the specified record and assign it to the property in the specified instance
        /// </summary>
        /// <param name="source">Database record</param>
        /// <param name="destination">Entity instance</param>
        /// <remarks>
        ///     <para><c>DBNull</c> will go through the adapter and/or be replaced with the <see cref="NullValue" />.</para>
        /// </remarks>
        void Map(IDataRecord source, object destination);

        /// <summary>
        ///     Get the property value (converted to a column value, i.e. run through the adapter and the null replacement check).
        /// </summary>
        /// <param name="entity">Entity to retrieve value from</param>
        /// <returns>Property value, adapted for insertion into the database row.</returns>
        object GetValue(object entity);

        /// <summary>
        ///     Set property value by specifying a column value (i.e. use the <c>ColumnToPropertyAdapter</c> when assigning the
        ///     value)
        /// </summary>
        /// <param name="entity">Entity to retrieve value from</param>
        /// <param name="columnValue">Column value</param>
        void SetProperty(object entity, object columnValue);
    }
}